console.log('console.log')
console.info('console.info')
console.error('console.error')
console.warn('console.warn')
console.log('console.table')
let tabla = [
  {
    nombre:'Andres',
    edad:32
  },
  {
    nombre:'Jose',
    edad:200
  }
]
console.table(tabla)
console.log('console.group:')
console.group('conversacion')
console.log('bla')
console.log('bla')
console.log('hola')
console.log('adios')
console.groupEnd('conversacion')
console.count('veces')
console.count('veces')
console.count('veces')
console.count('veces')
console.count('veces')
console.count('veces')
console.countReset(1)
console.count('veces')
